
server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/avrabie/config-server-demo01.git
          default-label: main